---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault
subjects:
- kind: ServiceAccount
  name: vault
roleRef:
  kind: Role
  name: vault-secrets-manager
  apiGroup: rbac.authorization.k8s.io
