language: go
go:
  - "1.11.x"

install:
  - go get github.com/Masterminds/glide
  - glide up -v

jobs:
  include:
    - stage: test
      script: make test
    - stage: Build and release
      script: make build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

